### ISSUE TITLE
java.io.IOException: The system cannot find the path specified

### ISSUE THREAD

**Issue by stageman21** [chrislo27/RhythmHeavenRemixEditor#242]
I'm trying to go on Rhythm Heaven Remix Editor 3 but every time I try to open it it doesn't work and then it will say "C:\Users\jamjar\Desktop\games\RHRE3_v3.11.0\Rhythm Heaven Remix Editor 3>java -jar RHRE3.jar
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.io.IOException: The system cannot find the path specified
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(Unknown Source)
        at io.github.chrislo27.toolboks.logging.SysOutPiper.pipe(SysOutPiper.kt:46)
        at io.github.chrislo27.toolboks.ToolboksGame.create(ToolboksGame.kt:90)
        at io.github.chrislo27.rhre3.RHRE3Application.create(RHRE3Application.kt:122)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)"
I have no idea what to do about it so I need you to help me.

**Comment by chrislo27** [comment]
This issue will be **indefinitely** closed because of the following reason(s):
* The [template](https://github.com/chrislo27/RhythmHeavenRemixEditor/blob/dev/.github/ISSUE_TEMPLATE.md) was removed, or filled out incorrectly
