### ISSUE TITLE
RHRE crashing after loading games

### ISSUE THREAD

**Issue by Supersmashgaming** [chrislo27/RhythmHeavenRemixEditor#286]
### Information

**Log file:**https://drive.google.com/file/d/1Z_8B3NaZkMFKiMLnkZeNYabPefm5D5mV/view?usp=sharing

**Editor version**: (insert relevant editor version here)

### Description
Every time the I open RHRE after loding some of the games it stop at a certain point and force close itself.

### Behaviours
**Expected behaviour**: Once opening RHRE it looks for SFX database updates afterwards start loading the games. Done successfully the application should go straight to the editor.

**Actual behaviour**: Opening RHRE fails to check for SFX database updates, tries loading games, and force close itself after a certain point.

## Steps to reproduce issue
1. Install latest version of RHRE (v3.18.0 as of 4/5/2019).
2. Launch RHRE application.
3. Application will stop loading games around games that start with S and force closes.

**Comment by dexiedoo** [comment]
Me and somebody else I know are having the same problem. Both of us seem to experience the crash almost always when loading the SFX for games starting with 'S.' I usually experience the crash at Space Soccer, personally.

**Comment by Hantyuuzin** [comment]
**It is written to log file.**

[DEBUG][LWJGL Application] Changed screens from io.github.chrislo27.rhre3.screen.GitUpdateScreen to io.github.chrislo27.rhre3.screen.RegistryLoadingScreen
com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (String)"// Under no circumstances should you attempt to modify this file.
// This is a special game definition containing required content for the editor to function.
{
  "series": "other",
  "id": "special,
  "name": "Special Entities",
  "gameGroup": "Special Entities",
  "groupDefault": true,
  "priority": 2,
  "noDisplay": true,
  "objects": [
    {
      "type": "endEntity",
      "id": "*_endEntity",
      "deprecatedIDs": [],
      "name": "End Remix"
    },
    {
      "type": "subtitleEntity",
"[truncated 1497 chars]; line: 5, column: 9] (through reference chain: io.github.chrislo27.rhre3.registry.json.GameObject["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:254)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at io.github.chrislo27.rhre3.registry.GameRegistry$RegistryData.loadOne(GameRegistry.kt:346)
	at io.github.chrislo27.rhre3.registry.GameRegistry$RegistryData.loadFor(GameRegistry.kt:627)
	at io.github.chrislo27.rhre3.screen.RegistryLoadingScreen.render(RegistryLoadingScreen.kt:93)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at io.github.chrislo27.toolboks.ToolboksGame.render(ToolboksGame.kt:190)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (String)"// Under no circumstances should you attempt to modify this file.
// This is a special game definition containing required content for the editor to function.
{
  "series": "other",
  "id": "special,
  "name": "Special Entities",
  "gameGroup": "Special Entities",
  "groupDefault": true,
  "priority": 2,
  "noDisplay": true,
  "objects": [
    {
      "type": "endEntity",
      "id": "*_endEntity",
      "deprecatedIDs": [],
      "name": "End Remix"
    },
    {
      "type": "subtitleEntity",
"[truncated 1497 chars]; line: 5, column: 19]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:669)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwUnquotedSpace(ParserMinimalBase.java:633)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2047)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2018)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getValueAsString(ReaderBasedJsonParser.java:321)
	at com.fasterxml.jackson.module.afterburner.deser.SettableStringFieldProperty.deserializeAndSet(SettableStringFieldProperty.java:47)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	... 10 more

**Comment by Supersmashgaming** [comment]
> Me and somebody else I know are having the same problem. Both of us seem to experience the crash almost always when loading the SFX for games starting with 'S.' I usually experience the crash at Space Soccer, personally.

Yeah it usually stop around space soccer and/or space dance

**Comment by mikethecat** [comment]
Mine also stops at Space Soccer at the France version.

**Comment by Supersmashgaming** [comment]
> ### Information
> **Log file:**https://drive.google.com/file/d/1Z_8B3NaZkMFKiMLnkZeNYabPefm5D5mV/view?usp=sharing
> 
> **Editor version**: (insert relevant editor version here)
> 
> ### Description
> Every time the I open RHRE after loding some of the games it stop at a certain point and force close itself.
> 
> ### Behaviours
> **Expected behaviour**: Once opening RHRE it looks for SFX database updates afterwards start loading the games. Done successfully the application should go straight to the editor.
> 
> **Actual behaviour**: Opening RHRE fails to check for SFX database updates, tries loading games, and force close itself after a certain point.
> 
> ## Steps to reproduce issue
> 1. Install latest version of RHRE (v3.18.0 as of 4/5/2019).
> 2. Launch RHRE application.
> 3. Application fail to load all games and force closes.

**Comment by dexiedoo** [comment]
Why is this tagged as invalid?

**Comment by mikethecat** [comment]
Looks like he fixed it, because RHRE works fine now.
